# Generated by Django 4.2.7 on 2025-05-03 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_email_teacherprofile_studentprofile'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата присоединения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='groups.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_groups', to='authentication.teacherprofile', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Преподаватель группы',
                'verbose_name_plural': 'Преподаватели групп',
                'ordering': ['group', 'joined_at'],
                'unique_together': {('group', 'teacher')},
            },
        ),
    ]
