# Generated by Django 4.2.7 on 2025-05-03 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_customuser_email_teacherprofile_studentprofile'),
        ('groups', '0002_groupteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'Архивировано')], default='draft', max_length=10, verbose_name='Статус')),
                ('deadline', models.DateTimeField(verbose_name='Срок сдачи')),
                ('max_points', models.PositiveIntegerField(default=100, verbose_name='Максимальное количество баллов')),
                ('allow_late_submissions', models.BooleanField(default=True, verbose_name='Разрешить сдачу после дедлайна')),
                ('late_penalty_percentage', models.PositiveIntegerField(default=0, verbose_name='Процент штрафа за позднюю сдачу')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to='authentication.teacherprofile', verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('submitted', 'Отправлено'), ('graded', 'Оценено'), ('returned', 'Возвращено на доработку')], default='submitted', max_length=10, verbose_name='Статус')),
                ('points', models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('is_late', models.BooleanField(default=False, verbose_name='Сдано после дедлайна')),
                ('feedback', models.TextField(blank=True, verbose_name='Обратная связь от преподавателя')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оценивания')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='Задание')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to='authentication.teacherprofile', verbose_name='Оценил')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='authentication.studentprofile', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Ответ на задание',
                'verbose_name_plural': 'Ответы на задания',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/attachments/', verbose_name='Файл')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assignments.submission', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вложение ответа',
                'verbose_name_plural': 'Вложения ответов',
            },
        ),
        migrations.CreateModel(
            name='AssignmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('custom_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Индивидуальный дедлайн')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_groups', to='assignments.assignment', verbose_name='Задание')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='groups.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Назначение задания группе',
                'verbose_name_plural': 'Назначения заданий группам',
                'unique_together': {('assignment', 'group')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignments/attachments/', verbose_name='Файл')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assignments.assignment', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Вложение задания',
                'verbose_name_plural': 'Вложения заданий',
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='groups',
            field=models.ManyToManyField(related_name='assignments', through='assignments.AssignmentGroup', to='groups.group', verbose_name='Назначенные группы'),
        ),
    ]
